services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    restart: "always"
    depends_on:
      - database
    links:
      - database
    volumes:
      - "${PWD}/public_html:/var/www/holonet.myria.dev/public_html"
      - "${PWD}/php:/var/www/holonet.myria.dev/php"
      - "/etc/letsencrypt:/etc/letsencrypt"
  database:
    image: mariadb
    restart: "always"
    volumes:
      - "${PWD}/mysql_database:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "holonet"

volumes:
  mysql_database:
    external: true
  php:
    external: true
  public_html:
    external: true



