services:
  web:
    build: .
    ports:
      - 8081:80
    restart: "always"
    depends_on:
      - database
    links:
      - database
    volumes:
      - "/home/opc/the_holonet_archives/public_html:/var/www/holonet.myria.dev/public_html"
      - "/home/opc/the_holonet_archives/php:/var/www/holonet.myria.dev/php"
  database:
    image: mariadb
    restart: "always"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "Aqpm9supk63X2z*A27qo9Mux"
      MYSQL_DATABASE: "holonet"

volumes:
  mysql_database:
    external: true
  php:
    external: true
  public_html:
    external: true



